CREATE TABLE IF NOT EXISTS tbl_user (
    OrgId UUID NOT NULL REFERENCES tbl_org (Id),
    Id UUID DEFAULT UUID_GENERATE_V4 () NOT NULL PRIMARY KEY,
    RoleId UUID NOT NULL REFERENCES tbl_user_role (Id),
    FirstName VARCHAR(64) NOT NULL,
    LastName VARCHAR(64) NOT NULL,
    EmailId VARCHAR(64) NOT NULL,
    ContactNo VARCHAR(10) NOT NULL,
    Status VARCHAR(8) NOT NULL,
    CreatedAt TIMESTAMP
);
