CREATE TABLE IF NOT EXISTS tbl_org_account (
    OrgId UUID NOT NULL REFERENCES tbl_org (Id),
    Id UUID DEFAULT UUID_GENERATE_V4 () NOT NULL PRIMARY KEY,
    Type VARCHAR(6) NOT NULL,
    FirmName VARCHAR(64) NOT NULL,
    FirstName VARCHAR(64) NOT NULL,
    LastName VARCHAR(64) NOT NULL,
    EmailId VARCHAR(64) NOT NULL,
    ContactNo VARCHAR(10) NOT NULL,
    Address VARCHAR(64) NOT NULL,
	City VARCHAR(50) NOT NULL,
	State VARCHAR(50) NOT NULL,
	Country VARCHAR(50) NOT NULL,
	ZipCode VARCHAR(6) NOT NULL,
    Status VARCHAR(8) NOT NULL,
    CreatedAt TIMESTAMP
);
