CREATE TABLE IF NOT EXISTS tbl_user_role (
    OrgId UUID NOT NULL REFERENCES tbl_org (Id),
    Id UUID DEFAULT UUID_GENERATE_V4 () NOT NULL PRIMARY KEY,
    Name VARCHAR(64) NOT NULL,
    BookieAccess BOOLEAN NOT NULL,
    BrokerAccess BOOLEAN NOT NULL,
    CreatedAt TIMESTAMP
);
