CREATE TABLE IF NOT EXISTS TblUser (
    OrgId UUID NOT NULL REFERENCES TblOrg (Id),
    Id UUID DEFAULT UUID_GENERATE_V4 () NOT NULL PRIMARY KEY,
    FirstName VARCHAR(64) NOT NULL,
    LastName VARCHAR(64) NOT NULL,
    EmailId VARCHAR(64) NOT NULL,
    ContactNo VARCHAR(10) NOT NULL,
    Status VARCHAR(8) NOT NULL,
    LoginDateTime TIMESTAMP,
    LoginFailTries SMALLINT,
    Password VARCHAR(25) NOT NULL
);
